bookapp/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin
from bookapp import views

app_name = "bookapp"

urlpatterns = [
	 url(r'search/$', views.searchslots, name='searchslots'),
	 url(r'book/$', views.Bookslot.as_view(), name='bookslot'),
	 url(r'confirm/$', views.confirmslot, name='confirmslot'),
	 url(r'mybookings/$', views.bookedslots, name='bookedslots'),
	 url(r'cancel/$', views.cancelslot, name='cancelslot'),

	 

]

bookmyslot/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = []
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns +=[
    path(r'accounts/', include('accounts.urls')),
    path(r'admin/', admin.site.urls),
    path(r'bookings/',  include('bookapp.urls')),
    path(r'master/', include('master.urls')),
    path(r'', include('gridapp.urls')),
]

master/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from master import views

app_name='master'

urlpatterns = [
       url(r'master/', views.master, name='master'),
       url(r'addslot/', views.addslot, name='addslot'),
       url(r'cropper/', views.cropper, name='cropper'),
       url(r'getslots/', views.sendSlotDims, name='getslots'),
       url(r'addarea/(?P<reqtype>\w+)', views.addarea, name='addarea'),
       url(r'genslots/', views.generateSlots, name='genslots'),
       url(r'fetch/', views.fetch, name='fetch'),
       url(r'save/', views.save, name='save'),
       url(r'removeslot/', views.removeslot, name='removeslot'),
       url(r'start/', views.startcnn.as_view(), name='start'),

]

bookapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from gridapp.models import SlotsCache, Slots
from django.db.models import Exists, OuterRef
from django.db.models import F
# Create your models here.


class ReservationsSet(models.QuerySet):
    def add_engaged(self):
        return self.annotate(
            engaged=Exists(SlotsCache.objects.filter(reservation_id=OuterRef('reservation_id'))
                ))
            

class Reservations(models.Model):
    reservation_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="reservations",
    )
    slot_id = models.ForeignKey(
    	Slots,
    	on_delete=models.SET_NULL, null=True,
        related_name="reservations")
    booking_time = models.DateTimeField( auto_now_add=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    confirmation = models.BooleanField(default=False)
    payment = models.IntegerField(primary_key=False, default=0)

    objects = ReservationsSet.as_manager()
    

class PenaltyReservations(models.Model):
    reservation_id = models.IntegerField(primary_key=True)
    slot_id = models.ForeignKey(
        Slots,
        on_delete=models.SET_NULL, null=True, related_name="pl")
    actual_end_time=models.DateTimeField()
    lastseen_time=models.DateTimeField(auto_now_add=True)

class UnauthorizedParkings(models.Model):
    start_time = models.DateTimeField(primary_key=True)
    slot_id = models.ForeignKey(
        Slots,
        on_delete=models.SET_NULL, null=True)
    lastseen_time = models.DateTimeField(auto_now_add=True)
       

bookapp/forms.py
from django import forms
from datetime import datetime, timedelta

class BookingSearchForm(forms.Form):
	startdate = forms.DateField(label="Start Date : ")
	starttime = forms.TimeField(label="Start Time : ")
	enddate = forms.DateField(label="End Date : ")
	endtime = forms.TimeField(label="End Time : ")
	curr_datetime=datetime.now()
	def clean(self):
		cleaned_data=super().clean()
		start_date=cleaned_data.get("startdate")
		end_date=cleaned_data.get("enddate")
		start_time=cleaned_data.get("starttime")
		end_time=cleaned_data.get("endtime")
		start_datetime=datetime.combine(start_date, start_time)
		end_datetime=datetime.combine(end_date, end_time)
		duration=end_datetime-start_datetime
		duration_min=divmod(duration.total_seconds(),60)[0]  
		if(start_datetime>end_datetime):
			raise forms.ValidationError(
                    "start date and time must be less than end date and time"
                )
		if(duration_min<=5):
			raise forms.ValidationError(
                    "minimum booking time is 5 min"
                )
		if(start_datetime<(self.curr_datetime-timedelta(minutes=5))):
			raise forms.ValidationError(
                    "start time should be greater than current time"
                )	
		self.cleaned_data.update(startdatetime=start_datetime)
		self.cleaned_data.update(enddatetime=end_datetime)


class BookingForm(BookingSearchForm):
	slotselected=forms.IntegerField()	
	

bookapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.shortcuts import render, reverse, redirect
import mysql.connector
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from datetime import datetime, timedelta
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Reservations
from gridapp.models import Slots, SlotsCache
from accounts.models import User
from django.db.models import Q
import json
import pytz
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import BookingSearchForm, BookingForm
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

@csrf_exempt
def searchslots(request):
    if(request.method=="POST"):
        form = BookingSearchForm(request.POST)
        if form.is_valid():
          print("valid form")
        else:
          print("not valid")
          return JsonResponse({"status":2,"message":form.errors})    
        print("request post data")
        print(str(request.POST))
        # request_data=request.POST["data"]
        # start_date=request.POST["startdate"]
        # end_date=request.POST["enddate"]
        # start_time=request.POST["starttime"]
        # end_time=request.POST["endtime"]
        # start_datetime=start_date + ' ' + start_time 
        # start_datetime=datetime.strptime(start_datetime,"%Y-%m-%d %H:%M")
        start_datetime=form.cleaned_data["startdatetime"]
        start_datetime=start_datetime.astimezone(pytz.utc)
        end_datetime = form.cleaned_data["enddatetime"]
        end_datetime=end_datetime.astimezone(pytz.utc)

        print(f"datetimes: st:  {start_datetime} et: {end_datetime}")
        q1=Reservations.objects.filter(start_time__lte=start_datetime, end_time__gte=start_datetime).only('slot_id')
        q2=Reservations.objects.filter(Q(start_time__range=(start_datetime, end_datetime-timedelta(minutes=1))) | Q(end_time__range=(start_datetime+timedelta(minutes=1), end_datetime))).only('slot_id')
        booked_slots=q1.union(q2)
        # print(str(booked_slots))
        booked_slots_list=list(map(lambda x: x.slot_id.slot_id, booked_slots))
        print(str(booked_slots_list))
        avaliable_slots=Slots.objects.exclude(slot_id__in=booked_slots_list).only('slot_id')
        avaliable_slots_list=list(avaliable_slots)
        list2=list(map(lambda x: x.slot_id, avaliable_slots))
        print(list2)
        #print(avaliable_slots_list[0].slot_id)
        grid_dict={}
        grid_dict["status"]=1
        booked_dict={}
        for i in booked_slots_list:
          booked_dict[i]=1;
        avaliable_dict={}
        for slot in avaliable_slots_list:
            avaliable_dict[slot.slot_id]=0   
        grid_dict["booked"]=booked_dict
        grid_dict["avaliable"]=avaliable_dict    
        print(grid_dict)    
        return JsonResponse(grid_dict) 

    return JsonResponse({"status":3}) 

class Bookslot(LoginRequiredMixin,View):
    login_url = '/'
    #redirect_field_name = 'redirect_to'
    def post(self, request):
        print("Entered book slot")
        print(str(request.POST))
        form=BookingForm(request.POST)
        if form.is_valid():
          print("valid")  
        else:
          messages.warning(request, 'form validation error please refresh and try again')
          return redirect(reverse('gridapp:index'))

        current_slot_id = form.cleaned_data["slotselected"]
        current_user = request.user
        current_slot = Slots.objects.get(slot_id=current_slot_id)
        # start_date=request.POST["sdate"]
        # end_date=request.POST["edate"]
        # start_time=request.POST["stime"]
        # end_time=request.POST["etime"]
        # start_datetime=start_date + ' ' + start_time 
        # start_datetime=datetime.strptime(start_datetime,"%Y-%m-%d %H:%M")
        start_datetime=form.cleaned_data["startdatetime"]
        start_datetime=start_datetime.astimezone(pytz.utc)
        # end_datetime=end_date + ' ' + end_time
        # end_datetime=datetime.strptime(end_datetime,"%Y-%m-%d %H:%M")
        end_datetime=form.cleaned_data["enddatetime"]
        end_datetime=end_datetime.astimezone(pytz.utc)
        print("start datetime: ", start_datetime, "enddattime: ", end_datetime)
        reservation_id=None
        try:
            with transaction.atomic():
                q1=Reservations.objects.filter(start_time__lte=start_datetime, end_time__gte=start_datetime).only('slot_id')
                q2=Reservations.objects.filter(Q(start_time__range=(start_datetime, end_datetime-timedelta(minutes=1))) | Q(end_time__range=(start_datetime+timedelta(minutes=1), end_datetime))).only('slot_id')
                booked_slots=q1.union(q2)
                print("len is : 0,", len(booked_slots))
                booked_slots_list=set(list(map(lambda x: x.slot_id.slot_id, booked_slots)))
                print("booked slots list is")
                print(booked_slots_list)
                if(int(current_slot_id) not in booked_slots_list):
                  new_reservation=Reservations(user_id=current_user, slot_id=current_slot, start_time=start_datetime,
                    end_time=end_datetime)
                  new_reservation.save()
                  reservation_id=new_reservation.reservation_id;
            if(reservation_id):      
                  diff=abs(start_datetime - end_datetime)
                  total_mins = (diff.days*1440 + diff.seconds/60)
                  amt=total_mins/60*10
                  amt=round(amt,2)
                  context={"slotselected":current_slot_id,"dst":start_datetime,"det":end_datetime,"amt":amt,
                  "st":form.cleaned_data["starttime"], "et": form.cleaned_data["endtime"], "name":request.user.email, "rid":reservation_id}
                  return render(request, "bookapp/confirm.html", context)
            else:
                  messages.warning(request, 'Slot is booked by another person, Please try again')
                  return redirect(reverse('gridapp:index'))
        except IntegrityError:
             messages.error(request, 'Database error refresh and try again')
             return redirect(reverse('gridapp:index'))

    def get(self, request):
        messages.error(request, 'Invalid request type')
        return redirect(reverse('gridapp:index'))    
        

@login_required
def confirmslot(request):
  if(request.method=="POST"):
    print(str(request.POST))
    reservation_id=int(request.POST["rid"])
    payment= int(float(request.POST["amount"]))
    try:
      current_reservation=Reservations.objects.get(reservation_id=reservation_id)
      print(current_reservation)
      current_reservation.confirmation=True;
      current_reservation.payment=payment
      current_reservation.save()
      return redirect("/bookings/mybookings")
    except Reservations.DoesNotExist:
      messages.warning(request, "Booking timed out, please try again")  
      return redirect(reverse('gridapp:index'))
  else:    
    messages.error(request, 'Invalid request type')
    return redirect(reverse('gridapp:index'))


@login_required
def bookedslots(request):
  if(request.method=="GET"):
    current_time=datetime.now()
    current_time=current_time.astimezone(pytz.utc)
    print("current time",current_time)
    current_user=request.user
    user_reservations=Reservations.objects.filter(user_id=current_user.id)
    ongoing_reservations=user_reservations.add_engaged().filter(start_time__lt=current_time,end_time__gt=current_time).values(
        'reservation_id','slot_id','start_time','end_time','booking_time','engaged')
    past_reservations=user_reservations.filter(end_time__lt=current_time)
    future_reservations=user_reservations.filter(start_time__gt=current_time)
    print(user_reservations)
    return render(request, "bookapp/userbookings.html",{"past":past_reservations,
        "future":future_reservations,"current":ongoing_reservations})
  else:
    messages.error(request, 'Invalid request type')
    return redirect(reverse('gridapp:index'))

@login_required
def cancelslot(request):
  if(request.method=="POST"):
    current_time=datetime.now()
    current_time=current_time.astimezone(pytz.utc)
    current_user=request.user;
    reservation_id=int(request.POST["reservation_id"]);
    print("reservation_id", reservation_id);
    res_obj = Reservations.objects.get(reservation_id=reservation_id)
    if res_obj.end_time < current_time:
        return JsonResponse({"status":5})  
    slot_query=SlotsCache.objects.filter(reservation_id=reservation_id, slot_id__occupied=True)
    if not slot_query:
      try:
        with transaction.atomic():
          res_obj.delete()
          current_reservation_cache=SlotsCache.objects.filter(reservation_id=reservation_id).update()
        return JsonResponse({"status":1,})
      except Exception as e:
        print(str(e))
      return JsonResponse({"status":2})   
    else:
      return JsonResponse({"status":3})  
  else:
    return JsonResponse({"status":4})               

bookapp/templates/bookapp/confirm.html
 
{% extends 'base.html' %}

{% block content %}

 <div class="row">
        <div class="col-xs-12 col-md-4 col-md-offset-4">
            <form role="form" action="{% url 'bookapp:confirmslot' %}" method="POST" >
                {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Payment Details
                    </h3>

                </div>
                <div class="panel-body">
                    
                      <div class="form-group">
                          <label>Booking at Slot {{slotselected}} from {{st}} to {{et}}</label>
                              <input class="form-control" type="hidden" name="rid" value="{{rid}}">
                              <input class="form-control" type="hidden" name="amount" value="{{amt}}">
                              <!-- <input class="form-control" type="hidden" name="slot" value="{{slotselected}}"> -->
                      </div>
                    <div class="form-group">
                        <label for="cardNumber">
                            CARD NUMBER</label>
                        <div class="input-group">
                            <input type="text" class="form-control" id="cardNumber" placeholder="Valid Card Number"
                                required autofocus />
                            <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-7 col-md-7">
                            <div class="form-group">
                              <div class="col-xs-12 col-lg-12">
                                <label for="expityMonth">
                                    EXPIRY DATE</label>
                              </div>
                                <div class="col-xs-6 col-lg-6 pl-ziro">
                                    <input type="text" class="form-control" id="expityMonth" placeholder="MM" required />
                                </div>
                                <div class="col-xs-6 col-lg-6 pl-ziro">
                                    <input type="text" class="form-control" id="expityYear" placeholder="YY" required /></div>
                            </div>
                        </div>
                        <div class="col-xs-5 col-md-5 pull-right">
                            <div class="form-group">
                                <label for="cvCode">
                                    CV CODE</label>
                                <input type="password" class="form-control" id="cvCode" placeholder="CV" required />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
           
            <input class="btn btn-success btn-lg btn-block" type="submit" value="Pay Rs.{{amt}}"/>
        </div>
    </div>

    <script type="text/javascript">
        
    </script>

    {% endblock %}

bookapp/templates/bookapp/userbookings.html
{% extends 'base.html' %}

{% block content %}

<!-- <div class="container-fluid"> -->

  <h2>My Bookings</h2>
  <br>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs">
    <li  class="active">
      <a data-toggle="tab" href="#ongoing">Current</a>
    </li>
    <li>
      <a data-toggle="tab" href="#future">Upcoming</a>
    </li>
    <li>
      <a data-toggle="tab" href="#past">Previous</a>
    </li>
  </ul>
  <div class="tab-content" style="margin-top:20px;">
     <!-- ongoing  -->
    <div id="ongoing" class="container tab-pane active">
      <h4>Currently Active Bookings</h4>
      <div class="table-responsive" style="border: none;">          
      <table class="table" id="mytab1" style="color: white;">
        <thead>
          <tr>
            <th>ID</th>
            
            <th>Slot</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Status</th>
            <th style="padding-left: 20px;">Cancel</th>
            
          </tr>
        </thead>
        <tbody>
          {% for item in current %}
          <tr id="r{{item.reservation_id}}">
            <td>{{item.reservation_id}}</td>
            <td >{{item.slot_id}}</td>
            <td>{{item.start_time}}</td>
            <td>{{item.end_time}}</td>
            <td>{% if item.engaged %}Parked {% else %}Not Parked{% endif %}</td>
            <td><button id="{{item.reservation_id}}" class="cancel btn btn-danger">Cancel</button>
            </td>
            
          </tr>
            {% endfor %}
        </tbody>
      </table>
     </div>
   </div>
 <!-- future  -->
    <div id="future" class="container tab-pane">
      <div class="table-responsive" style="border: none;"> 
            <h4>Upcoming Bookings</h4>         
      <table class="table" id="mytab1" style="color: white;">
        <thead>
          <tr>
            <th>ID</th>
            
            <th>Slot</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th style="padding-left: 20px;">Cancel</th>
            
          </tr>
        </thead>
        <tbody>
          {% for item in future %}
          <tr id="r{{item.reservation_id}}">
            <td>{{item.reservation_id}}</td>
            <td >{{item.slot_id_id}}</td>
            <td>{{item.start_time}}</td>
            <td>{{item.end_time}}</td>
            <td><button id="{{item.reservation_id}}" class="cancel btn btn-danger">Cancel</button>
            </td>
            
          </tr>
            {% endfor %}
        </tbody>
      </table>
     </div>
   </div>

   <!-- past  -->

    <div id="past" class="container tab-pane">
      <h4>Previous Bookings</h4>    
      <div class="table-responsive" style="border: none;">          
      <table class="table" id="mytab1" style="color: white;">
        <thead>
          <tr>
            <th>ID</th>
            
            <th>Slot</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th style="padding-left: 20px;">Cancel</th>
            
          </tr>
        </thead>
        <tbody>
          {% for item in past %}
          <tr id="r{{item.reservation_id}}">
            <td>{{item.reservation_id}}</td>
            <td >{{item.slot_id_id}}</td>
            <td>{{item.start_time}}</td>
            <td>{{item.end_time}}</td>
            <td>Not applicable</td>       
          </tr>
            {% endfor %}
        </tbody>
      </table>
     </div>
   </div>
  
</div>
<!-- </div> -->

<script>
    (function(window, location) {
history.replaceState(null, document.title, location.pathname+"#!/history");
history.pushState(null, document.title, location.pathname);

window.addEventListener("popstate", function() {
  if(location.hash === "#!/history") {
    history.replaceState(null, document.title, location.pathname);
    setTimeout(function(){
      location.replace("/grid/grid");
    },0);
  }
}, false);
}(window, location));
  </script>

<script type="text/javascript">

  $( document ).ready(function() {

    $(".cancel").click(function(event){
      reservation_id=$(this).attr('id');
      $.ajax({
        type: 'POST',
        url: "{% url 'bookapp:cancelslot' %}",
        data: {"reservation_id":reservation_id,} ,
        dataType : 'json',
        success: function(response) { 
         let status=response["status"]
         if(status==1){
           $("#r"+ reservation_id).remove()
         }
         else if(status==2){
            alert("If you are already parked, please move your car before canceling")
         }
         else if(status==5){
            alert("Your reservation as already expired no need canceling")
         }
         else{
           alert("try again")
         }
       },
    });
    })
   }); 
// setInterval(function() {
// // var d = new Date();
// // var t={{item.2.time}};
// // var ct=d.getHours()+":"+d.getMinutes();
// //   if(t >= ct ){
// //     document.getElementById("cancelbtn").disabled = true;

// //   }
// //   var table = document.getElementById("mytab1");
// for (var i = 1, row; row = table.rows[i]; i++) {

//    // for (var j = 0, col; col = row.cells[j]; j++) {
      
//    // } 
//    var d = new Date();
//     var t=document.getElementsByClassName("table")[0].rows[i].cells[2];
//     var ct=d.getHours()+":"+d.getMinutes();
//     if(t >= ct ){
//     // document.getElementsByClassName("table")[0].rows[i].cells[5].childNodes[0].disabled = true;
//     document.getElementsByClassName("table")[0].rows[i].cells[4].style.backgroundColor="green";

//   } 
// }
 
// }, 60000);

</script>

{% endblock %}