bookapp/urls.py
from django.conf.urls import url
from django.conf.urls import include

from django.contrib import admin
from bookapp import views

app_name = "bookapp"

urlpatterns = [
	 url(r'search/$', views.searchslots, name='searchslots'),
	 url(r'book/$', views.Bookslot.as_view(), name='bookslot'),
	 url(r'confirm/$', views.confirmslot, name='confirmslot'),
	 url(r'mybookings/$', views.bookedslots, name='bookedslots'),
	 url(r'cancel/$', views.cancelslot, name='cancelslot'),

	 

]

bookmyslot/urls.py
from django.contrib import admin
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = []
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns +=[
    path(r'accounts/', include('accounts.urls')),
    path(r'admin/', admin.site.urls),
    path(r'bookings/',  include('bookapp.urls')),
    path(r'master/', include('master.urls')),
    path(r'', include('gridapp.urls')),
]

gridapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from gridapp import views

app_name="gridapp"
urlpatterns = [
      url(r'^getslots/(?P<restype>\w+)/', views.getslots, name='getslots'),
      url(r'^scan/', views.qrscan, name='qrscan'),
      url(r'^getdata/', views.getdata, name='getdata'),
      url(r'^$', views.getslots, {'restype': 'html'}, name='index'),

]

master/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from master import views

app_name='master'

urlpatterns = [
       url(r'master/', views.master, name='master'),
       url(r'addslot/', views.addslot, name='addslot'),
       url(r'cropper/', views.cropper, name='cropper'),
       url(r'getslots/', views.sendSlotDims, name='getslots'),
       url(r'addarea/(?P<reqtype>\w+)', views.addarea, name='addarea'),
       url(r'genslots/', views.generateSlots, name='genslots'),
       url(r'fetch/', views.fetch, name='fetch'),
       url(r'save/', views.save, name='save'),
       url(r'removeslot/', views.removeslot, name='removeslot'),
       url(r'start/', views.startcnn.as_view(), name='start'),

]

gridapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Slots(models.Model):
    slot_id = models.AutoField(primary_key=True)
    occupied = models.BooleanField()
    cnn_timestamp = models.DateTimeField()
    cnnflag = models.BooleanField(default=False)
    confidence = models.IntegerField(primary_key=False, default=0)

class SlotsCache(models.Model):
    slot_id = models.OneToOneField(
        Slots,
        on_delete=models.CASCADE,
        related_name='slot_cache',
    )
    reservation_id = models.IntegerField(primary_key=False, null=True)
    end_time = models.DateTimeField(null=True)

gridapp/forms.py
from django import forms


	

gridapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.utils import timezone
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from datetime import datetime, timedelta
from django.http import JsonResponse
from .models import Slots, SlotsCache
from master.models import  SlotDims, ParkingAreas, RenderDims
from bookapp.models import Reservations
import json
import pytz
import time
import os
import mysql.connector
import itertools
from django.db.models import Sum, Avg, Max




CNNDELAY = 2

@csrf_exempt
def getdata(request):
 if(request.method=="POST"):
  data=request.POST["val"]
  cnnts=request.POST["ts"][:19]
  cnnts=datetime.strptime(cnnts,"%Y-%m-%d %H:%M:%S")
  #cnnts=cnnts.astimezone(pytz.utc)
  print(cnnts)
  details=json.loads(data)
  detailsplain={}
  db = mysql.connector.connect(user='django', password='virurohan', 
                                database='bookmyslot')
  cursor = db.cursor()
  #cur= db.cursor()
  cursor.execute('SELECT slot_id,occupied, confidence FROM gridapp_slots')
  result = cursor.fetchall()
  
  for i, j in details.items():
    
   k=i
   l=j
   detailsplain[k]=l
  datatuple=tuple(detailsplain.items())
  slot_len=len(datatuple)
  
  for i in range(slot_len):
   if(datatuple[i][1]=="True" and result[i][1]==0):
    print("change")
    q="""UPDATE gridapp_slots SET occupied = %s, cnnflag = %s, cnn_timestamp = %s, confidence = %s WHERE slot_id = %s ;"""
    d=(1,1,cnnts,0,datatuple[i][0])
    cursor.execute(q,d) 
   elif(datatuple[i][1]=="False" and result[i][1]==1):
    print("change to free : ", datatuple[i][0])
    q="""UPDATE gridapp_slots SET occupied = %s, cnnflag = %s, cnn_timestamp = %s, confidence = %s WHERE slot_id = %s ;"""
    d=(0,0,cnnts,0,datatuple[i][0])
    cursor.execute(q,d) 
   else:
    print("no change")
    q="""UPDATE gridapp_slots SET confidence = %s WHERE slot_id = %s ;"""
    d=(result[i][2] + 1, datatuple[i][0])
    cursor.execute(q, d)
  db.commit()
  cursor.close()
  db.close()
  return HttpResponse("succs")


def getslots(request, restype):
    if(request.method=="GET"):
        slot_list = Slots.objects.order_by('slot_id')
        query2 = ParkingAreas.objects.filter(is_active=True).order_by('-area_id')
        if not query2:
          return render(request, "gridapp/grid.html", {"result":None, "st":timezone.now(), "area":None, "centertext":None,"noarea":"Please add an area"})
        # maxrow=SlotDims.objects.all().aggregate(Max('row'))['row__max']  
        print("max row")
        count=Slots.objects.count()
        if count <1:
          return render(request, "gridapp/grid.html", {"result":None, "st":timezone.now(), "area":None, "centertext":None,"noarea":"Please generate slots from admin page"})
        query2=query2[0]
        # area=(query2.width, query2.height)
        area_id=query2.area_id
        height = 75
        height=(height/query2.height)*700
        width= 50
        width=(width/query2.width)*500
        halfheight=int(height/2)
        halfwidth=int(width/2)
        centertext=(halfwidth-10, halfheight-10)
        area=(400, 700, width, height)
        print("area_id",area_id)
        # slot_dims = SlotDims.objects.filter(area_id__area_id=area_id, updated=True).order_by('row')
        render_dims=RenderDims.objects.all()
        print("slot_list", slot_list)
        if restype=="html":
            grid_dict = {} #list of tuples of format (id, occupied)
            for slot in slot_list:
                if(slot.occupied):
                    grid_dict[slot.slot_id]=(1,)
                else:
                    grid_dict[slot.slot_id]=(0,)
            for dim in render_dims:
                sid=dim.slot_id
                xpos=dim.x_left
                ypos=dim.y_left
                gs = grid_dict[sid]
                grid_dict[sid] = gs + (ypos, xpos)         

            # print(grid_dict)
            # startrow=1
            # xpos=10
            # ypos=10
            
            # incheight=height +10
            # incwidth=width + 10
            
            # for dim in slot_dims:
            #   sid=dim.slot_id
            #   if(dim.row>startrow):
            #     xpos=10
            #     ypos+=incheight
            #     startrow=dim.row
            #   gs=grid_dict[sid]  
            #   grid_dict[sid]=gs+ (xpos,ypos)
            #   xpos+=incwidth
            # print(grid_dict)  
            return render(request, "gridapp/grid.html", {"result":grid_dict, "st":timezone.now(), "area":area, "centertext":centertext})
        else:
            grid_dict={}
            for slot in slot_list:
                 if(slot.occupied):
                 	grid_dict[slot.slot_id]=1
                 else:
                    grid_dict[slot.slot_id]=0 	
            print(grid_dict)        
            return JsonResponse(grid_dict) 

    else:
        messages.error(request, 'Invalid request type')
        return redirect(reverse('gridapp:index'))     

# def getdata2(request):
#   if(request.method=="POST"):
#     cnn_data=request.POST["val"]
#     cnn_timestamp=request.POST["ts"]
#     cnn_timestamp=float(cnn_timestamp)
#     cnn_timestamp = datetime.fromtimestamp(cnn_timestamp / 1e3)
#     details=json.loads(data)


@csrf_exempt
def qrscan(request):
  resdict={}
  if not request.user.is_authenticated:
    resdict["status"] =-1
    return JsonResponse(resdict)

  if(request.method=="POST"):
    received_json_data=json.loads(request.body)
    current_slot=int(received_json_data["slot_id"])
    user_id=request.user.id
    print("user id ", user_id)
    print("slot_id id ", current_slot)
    current_datetime=datetime.now()
    current_datetime=current_datetime.astimezone(pytz.utc)
    print("current datetime", current_datetime)
    reservation_query = Reservations.objects.filter(user_id=user_id, slot_id=current_slot,
      start_time__lt=current_datetime, end_time__gt=current_datetime,
      confirmation=True).only('slot_id', 'end_time', 'start_time')
    # r1=Reservations.objects.get(reservation_id=5)
    # print("r1; ", r1.start_time, r1.end_time)
    print(reservation_query)
    if reservation_query:
      print("qr scan check")
      resdict["status"]=1
      current_reservation = reservation_query[0]
      slot_obj = Slots.objects.get(slot_id=current_slot)
      car_check_flag = True
      while(True):
        if(slot_obj.occupied==True):
          try:
            slotcache_obj=SlotsCache.objects.get(slot_id=current_slot)
            if not slotcache_obj.reservation_id==None:
              resdict["status"] = 3
              return JsonResponse(resdict)
            else:
              # obj, created = Pe.objects.update_or_create(
              # first_name='John', last_name='Lennon',
              # defaults={'first_name': 'Bob'},
              # )
              slotcache_obj.reservation_id=current_reservation.reservation_id
              slotcache_obj.end_time=current_reservation.end_time
              slotcache_obj.save()
              break
          except SlotsCache.DoesNotExist:
            new_slot_cache=SlotsCache(slot_id=slot_obj,
              reservation_id=current_reservation.reservation_id, end_time=current_reservation.end_time)
            new_slot_cache.save()
            break 
        else:
          if car_check_flag:
            time.sleep(CNNDELAY)
            car_check_flag = False
          else:
            print("no car detected")
            resdict["status"] = 4
            return JsonResponse(resdict)    
      print("booking confirmed")
      return JsonResponse(resdict)
    else: 
      resdict["status"]=2
      print("you have not booked seat")
      return JsonResponse(resdict) 
  else:
    resdict["status"]=0
    return JsonResponse(resdict)     














 

gridapp/templates/gridapp/grid.html

{% extends 'base.html' %}

{% block content %}


<!-- <div class="container" height="100%"> -->
  

    <!-- {% if alert %}
    <div class="alert alert-info alert-dismissible">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <strong>Sorry</strong> {{alert}}
    </div>
    {% endif %} -->
  <div class="row">
    {% if noarea %}
    <h4 style="color:#ffffff">Please add an Area</h4>
    {% endif %}
   
  </div>  
  <div class="row">
  <form id="search" class="form-inline" action="{% url 'bookapp:searchslots' %}" method="POST">
    <!-- {% csrf_token %} -->
  	<div class="form-group">
      <label style=" font-size: 15px; color: white;  margin: 0;">Start Date:</label>
      <input id="sdate" class="form-control" type="date" name="startdate" required="required" onblur="document.getElementById('dst').value = this.value;" >
      <input id="stime" class="form-control" type="time" name="starttime" required="required" onblur="document.getElementById('st').value = this.value;" >
    </div>
      <div class="form-group">
      <label style=" font-size: 15px; color: white;  margin: 0;">  End Date:</label>
      <input id="edate" class="form-control" type="date" name="enddate" required="required" onblur="
      document.getElementById('det').value = this.value;" >
      <input id="etime" class="form-control" type="time" name="endtime" required="required"  onblur="document.getElementById('et').value = this.value;" >
      </div>
    <input class="btn btn-primary" value="search" type="submit"/>
  </form>
      <div class="alert alert-warning" role="alert" id="searchalert" style="display:none">
         <button type="button" class="close" onclick="$('#searchalert').css('display','none')">&times;</button>
         <div class="message">
        This is a warning alert—check it out!
        </div>
      </div>
  </div>
  <div class="row top-buffer">

    <form id="bookform" action="{% url 'bookapp:bookslot' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="startdate" id="dst">
      <input type="hidden"  name="enddate" id="det">
      <input type="hidden" name="starttime" id="st">
      <input type="hidden"  name="endtime" id="et">
      <input id="slotselected" type="hidden" name="slotselected" required="required">
      <!-- <input class="btn btn-primary" id="book-button" type="submit" value="Book selected Slot"> -->
    </form>

    <div class="btn-group blocks">
      <button type="button" class="btn btn-primary" id="check-slots">Check Current Slot avaliability</button>
    </div>
    <div class="btn-group blocks">
      <button type="submit" form="bookform" class="btn btn-primary disabled" id="book-button">Book Selected Slot</button>
  </div>
  </div>

  <div class="row top-buffer">
    <div class="col" align="center">
  <h4 class="font-weight-bold" id ="datetimedisplay" style="color: white;">"Here is the live parking lot status. Red is occupied, green is free. Specify date and search to find an open slot and book it"</h4>
  </div>
</div>
<!-- </div> -->
<!--   <button class="btn btn-primary" id="check-slots">Check Current Slot availability</button>
</div> -->

  <div class="row flex-grow-1">
  
    <div class="col-lg-10 col-sm-12 col-md-12" id="gridwrap" style="text-align: center; overflow-y:auto;height:400px;overflow-x: auto">
  
   
    <svg class="bg" style="margin:20px auto; display: block; overflow:visible;" height="{{area.1}}" width="auto">
        {% for id, obj in result.items %}
        
        <g class="slotblock" id="g{{id}}">
          <rect id="r{{id}}" x="{{obj.1}}" y="{{obj.2}}" width="{{area.2}}" height="{{area.3}}"  class="{%if st %}{% if obj.0 %}  redrect {% else %}  greenrect {% endif %} {%endif%}"  style="stroke-width:3;stroke:rgb(0,0,0);cursor:{% if obj.0 %} not-allowed {% else %} pointer {% endif %} ;"></rect>
        <text x="{{obj.1|add:centertext.0}}" y="{{obj.2|add:centertext.1}}" font-size="15" fill="black"> {{id}} </text>
        </g>
       {% endfor %}
      </svg>
  

    </div>
  </div>


   <div class="row">
  </div>


<!-- </div> -->

<script type="text/javascript">

function updateSlots(grid_dict){       
  for(var slot in grid_dict){
  element = document.getElementById("r"+slot);
      if(grid_dict[slot]==1){
        element.classList.add("redrect");
        element.classList.remove("greenrect");
        element.style.cursor="not-allowed";
      }
      else{
        element.classList.add("greenrect");
        element.classList.remove("redrect");
        element.style.cursor="pointer";
      }       
   }
}

function ajaxSlots(){
  if(!$.active){
    $.ajax(
    {
        type:"GET",
        url: "/getslots/json/",
        dataType : 'json',

        success: function( data ){
          console.log("ajax slots")
          updateSlots(data);
        }

    });
  }       
}

// function pollSlots(slotobj, interval){
 
      
//     },interval);
// }

// function getDateTime(){

//     let startdate = $('#sdate').value
//     let starttime = $('#stime').value
//     var enddate = $('#edate').value
//     var endtime = $('#stime').value
// }


// var  = new Promise(function(resolve, reject) {
//   setTimeout(function() {
//     resolve('foo');
//   }, 300);

function searchSlots(slotobj) {
  //if(!$.active){
    let startdate = $('#sdate').val();
    let starttime = $('#stime').val();
    let enddate = $('#edate').val();
    let endtime = $('#etime').val();

    $.ajax({
        type: 'POST',
        url: $('#search').attr('action'),
        data: $('#search').serialize(), 
        dataType : 'json',
        success: function(response) { 
         if(response["status"]==1){
           slotobj.setResultdict(response["avaliable"], startdate, enddate, starttime, endtime);
           slotobj.change();
           $('#searchalert').hide();
           console.log(startdate + ' hehe ')
           updateSlots(response["booked"]); 
           updateSlots(response["avaliable"]); 
        }
        else if(response["status"]==2){
          let alertelm=$('#searchalert');
          slotobj.disableBooking();
          $("#datetimedisplay").html("")
          $('.message', alertelm).html(response["message"]["__all__"]);
          alertelm.css('display','block');
        }
        else{
          alert("invalid request")
        }
        
       },
    });
   //} 
}


$( document ).ready(function() {
    var slotobj = new CurrSlot(null);
    slotobj.change()
    // setInterval(function(){
    //   console.log("check")
    //   if(!slotobj.checkBookingStatus()){
    //     ajaxSlots()
    //   }}, 2000);

    $('#search').on('submit', function(event){
        event.preventDefault();
        $('#book-button').removeClass('btn-danger')
        //$('#book-button').addClass('btn-primary')
        $('#book-button').addClass('disabled')
        searchSlots(slotobj);
    });

    $(".slotblock").click(function(event) {
        let blockId = event.target.id;
        blockId = blockId.substring(1,);
        console.log(blockId);
        slotobj.test(blockId);
    });

    $("#check-slots").click(function(event) {
        slotobj.disableBooking();
        slotobj.change();
        $('#searchalert').hide();
        ajaxSlots();
    });
    $("#bookform").submit(function(event){
      let loginStatus=false;
      {% if user.is_authenticated %} loginStatus=true {% endif %}
      let bookingStatus = slotobj.checkBookingStatus();
      if(loginStatus && bookingStatus){
        return true;
      }
      else{
        event.preventDefault();
        if(!loginStatus){
          alert("Please Login");
        }
        else{
          alert("Please search and select a slot to book")
        }
      } 
    });

    // jQuery.validator.addMethod("checkbookingstatus", function(value, element) {
    //    return slotobj.checkBookingStatus();
    // }, "Please search and select a slot");

    //  jQuery.validator.addMethod("checklogin", function(value, element) {
    //    let loginStatus=false;
    //    {% if user.is_authenticated %} loginStatus="true" {% endif %}
    //    return loginStatus;
    // }, "Please search and select a slot");


    // $('#bookform').validate({ // initialize the plugin
    //     rules: {
    //         sdate: {
    //             required: true,
    //         },
    //         edate: {
    //             required: true,
    //         },
    //         stime: {
    //             required: true,
    //         },
    //         etime: {
    //             required: true,
    //         },
    //         slotselected: {
    //             required: true,
    //             checkbookingstatus:true,
    //             checklogin:true,
    //         },
    //     }
    // });


});    



</script>



{% endblock %}
